remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Surihix's tools
description: A Collection of tools made for modding and file related operations
