remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Surihix's tools
description: A Collection of tools made for modding games, extracting data from game resource archives and for other file related operations

github:
  zip_url: https://github.com/Surihix
  another_url: Github profile
